Ablog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('blog.urls')),
    path('user/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls')),

]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog.views import views_article
from blog.views import views_category


urlpatterns = [
    path("", views_article.HomeView.as_view(), name="home"),
    path("create_post/", views_article.ArticleCreateView.as_view(), name="article_create"),
    path("<int:pk>/detail/", views_article.ArticleDetailView.as_view(), name="article_detail"),
    path("<int:pk>/update/", views_article.ArticleUpdateView.as_view(), name="article_update"),
    path("<int:pk>/delete/", views_article.ArticleDeleteView.as_view(), name="article_delete"),

    path("categories/", views_category.CategoryView.as_view(), name="categories"),
    path("create_category/", views_category.CategoryCreateView.as_view(), name="category_create"),
    path("category/<int:id>/detail/", views_category.CategoryDetailView, name="category_detail"),
    path("category/<int:pk>/update/", views_category.CategoryUpdateView.as_view(), name="category_update"),
    path("category/<int:pk>/delete/", views_category.CategoryDeleteView.as_view(), name="category_delete"),

]

user/urls.py
from django.urls import path

from user import views

urlpatterns = [
    path("register/", views.UserRegister.as_view(), name="register"),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    title = models.CharField(
        max_length=55,
    )

    def get_absolute_url(self):
        return reverse("categories")


class Article(models.Model):
    title = models.CharField(
        max_length=255,
    )
    description = models.TextField()
    image = models.ImageField(
        null=True,
        blank=True,
        upload_to="images/",
    )

    user_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    category_id = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
    )

    def get_absolute_url(self):
        return reverse('article_detail', args=(str(self.id),))

user/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms

from blog.models import Article, Category


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = (
            'title',
            'description',
            'image',
            'user_id',
            'category_id'
        )

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'This is Title Placeholder'
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'This is Title Description'
                }
            ),
            'image': forms.FileInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'user_id': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'value': '',
                    'id': 'elder',
                    'type': 'hidden'
                }
            ),
            'category_id': forms.Select(
                attrs={
                    'class': 'form-control'
                }
            ),
        }


class ArticleUpdateForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = (
            'title',
            'description',
            'category_id',
            'image'
        )

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'This is Title Placeholder'
                }
            ),
            'description': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'This is Title Description'
                }
            ),
            'image': forms.FileInput(
                attrs={
                    'class': 'form-control'
                }
            ),
            'category_id': forms.Select(
                attrs={
                    'class': 'form-control'
                }
            ),
        }


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = ('title',)

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'This is Title Placeholder'
                }
            ),
            }

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'class': 'form-control'}
        )
    )

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)

        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

blog/views/views_article.py
from django.urls import reverse_lazy
from django.views import generic

from blog.forms import ArticleForm, ArticleUpdateForm
from blog.models import Article


class HomeView(generic.ListView):
    model = Article
    template_name = "home.html"


class ArticleCreateView(generic.CreateView):
    model = Article
    form_class = ArticleForm
    template_name = "article/create_post.html"

    def form_valid(self, form):
        form.instance.user = self.request.user

        # Save the image
        form.instance.image = form.cleaned_data['image']

        return super().form_valid(form)


class ArticleDetailView(generic.DetailView):
    model = Article
    template_name = "article/article_detail.html"


class ArticleUpdateView(generic.UpdateView):
    model = Article
    form_class = ArticleUpdateForm
    template_name = "article/article_update.html"


class ArticleDeleteView(generic.DeleteView):
    model = Article
    template_name = "article/article_delete.html"
    success_url = reverse_lazy("home")

blog/views/views_category.py
from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy
from django.views import generic

from blog.forms import CategoryForm
from blog.models import Article, Category


class CategoryView(generic.ListView):
    model = Category
    template_name = "category/category.html"


class CategoryCreateView(generic.CreateView):
    model = Category
    form_class = CategoryForm
    template_name = "category/category_create.html"


def CategoryDetailView(request, id):
    category = get_object_or_404(Category, id=id)
    category_article = Article.objects.filter(category_id=category)
    return render(request, 'category/category_detail.html', {'articles': category_article})


class CategoryUpdateView(generic.UpdateView):
    model = Category
    form_class = CategoryForm
    template_name = "category/category_update.html"


class CategoryDeleteView(generic.DeleteView):
    model = Category
    template_name = "article/article_delete.html"
    success_url = reverse_lazy("home")

user/views.py
from django.urls import reverse_lazy
from django.views import generic

from user.forms import SignUpForm


class UserRegister(generic.CreateView):
    form_class = SignUpForm
    template_name = "registration/registration.html"
    success_url = reverse_lazy('login')

templates/article/article_delete.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}

<h1>Delete Article</h1>
<br/><br/>

<h3>Delete: {{ article.title }}</h3>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}

    <strong>Are you sure?</strong><br/>
    <button class="btn btn-danger">Delete</button>
</form>

{% else %}
    <h1> You are not allowed!!!!</h1>
{% endif %}

{% endblock content %}

templates/article/article_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
        <div class="col-md-4">
          <img src="{{ article.image.url }}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Title: {{ article.title }}</h5>
            <h5 class="card-title">Created By: {{ article.user_id.username }}</h5>
            <p class="card-title">Category: {{ article.category_id.title }}</p>

            <p class="card-text">{{ article.description}}</p>
            {% if user.is_authenticated %}
                {% if user.id == article.user_id.id %}
                <a href="{% url 'article_update' article.pk%}"  class="btn btn-success">
                Update
                </a>
                <a href="{% url 'article_delete' article.pk%}" class="btn btn-danger">
                Delete
                </a> <br/>
                </li>
                {% endif %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>


<br/><br/>
<a href="{% url 'home' %}" class="btn btn-secondary">Back</a>
{% endblock %}

templates/article/article_update.html
{% extends 'base.html' %}

{% block content %}

{% if user.is_authenticated %}

<h1>Update Article</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-primary">Update</button>
</form>

{% else %}
    <h1> You are not allowed!!!!</h1>
{% endif %}

{% endblock content %}

templates/article/create_post.html
{% extends 'base.html' %}

{% block content %}

<h1>Create Article</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-primary">Article</button>
</form>

    <script>
    var name = "{{ user.id }}"
    document.getElementById("elder").value=name;
    </script>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
  </head>
  <body>

    {% include "include/navbar.html" %}

    <div class="container">
      {% block content %}

      {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
  </body>
</html>

templates/category/category.html
{% extends 'base.html' %}

{% block content %}


    {% for article in category_list %}

        <div class="card w-50">
          <div class="card-body">
              <a href="{% url 'category_detail' article.pk %}">
            <h5 class="card-title">{{ article.title }}</h5>
              </a>
                <a class="btn btn-success" href="{% url 'category_update' article.pk%}">
                Update
                </a>
                <a class="btn btn-danger" href="{% url 'category_delete' article.pk%}">
                Delete
                </a>
          </div>
        </div><br/>

    {% endfor %}

{% endblock %}

templates/category/category_create.html
{% extends 'base.html' %}

{% block content %}

<h1>Create Category</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <button class="btn btn-primary">Category</button>
</form>
{% endblock content %}

templates/category/category_detail.html
{% extends 'base.html' %}

{% block content %}

{% for article in articles %}

<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
        <div class="col-md-4">
          <img src="{{ article.image.url }}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Title: {{ article.title }}</h5>
            <h5 class="card-title">Created By: {{ article.user_id.username }}</h5>
            <p class="card-text">{{ article.description|slice:":150"}}</p>
            <a href="{% url 'article_detail' article.pk %}" class="btn btn-info">Go somewhere</a><br/><br/>
            {% if user.is_authenticated %}
                {% if user.id == article.user_id.id %}
                <a href="{% url 'article_update' article.pk%}"  class="btn btn-success">
                Update
                </a>
                <a href="{% url 'article_delete' article.pk%}" class="btn btn-danger">
                Delete
                </a> <br/>
                </li>
                {% endif %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>

{% endfor %}
{% endblock %}

templates/category/category_update.html
{% extends 'base.html' %}

{% block content %}


{% if user.is_authenticated %}

    <h1>Update Category</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}

        <button class="btn btn-primary">Category</button>
    </form>

{% else %}
    <h1> You are not allowed!!!!</h1>
{% endif %}

{% endblock content %}

templates/home.html
{% extends 'base.html' %}

{% block content %}

{% for article in object_list %}

<div class="card mb-3" style="max-width: 540px;">
  <div class="row g-0">
        <div class="col-md-4">
          <img src="{{ article.image.url }}" class="img-fluid rounded-start" alt="...">
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title">Title: {{ article.title }}</h5>
            <h5 class="card-title">Created By: {{ article.user_id.username }}</h5>
            <p class="card-text">{{ article.description|slice:":150"}}</p>
            <a href="{% url 'article_detail' article.pk %}" class="btn btn-info">Go somewhere</a><br/><br/>
            {% if user.is_authenticated %}
                {% if user.id == article.user_id.id %}
                <a href="{% url 'article_update' article.pk%}"  class="btn btn-success">
                Update
                </a>
                <a href="{% url 'article_delete' article.pk%}" class="btn btn-danger">
                Delete
                </a> <br/>
                </li>
                {% endif %}
            {% endif %}
          </div>
        </div>
      </div>
    </div>

{% endfor %}
{% endblock %}

templates/include/navbar.html
  <nav class="navbar navbar-dark  navbar-expand-lg bg-dark">
  <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>

              {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article_create' %}">Create Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'category_create' %}">Create Category</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                </li>

              {% endif %}

            {% if not user.is_authenticated %}

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Auth Dropdown
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'register' %}">Register</a></li>
                    <li><a class="dropdown-item" href="{% url 'login' %}">Login</a></li>

                  </ul>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'categories' %}">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'home' %}">Articles</a>
            </li>

          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
  <br/>